// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOfzmOv7lBP0y8tJyr9NOXswmH9HfIrDI',
    appId: '1:188098793596:web:e072263adb911410df39f9',
    messagingSenderId: '188098793596',
    projectId: 'minchat-8ea90',
    authDomain: 'minchat-8ea90.firebaseapp.com',
    storageBucket: 'minchat-8ea90.appspot.com',
    measurementId: 'G-K57FRS4TVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4LTMU9W_Vme7Wlm3olWwsT1FQ-wrY4FU',
    appId: '1:188098793596:android:ea7e5b95720db609df39f9',
    messagingSenderId: '188098793596',
    projectId: 'minchat-8ea90',
    storageBucket: 'minchat-8ea90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnX4dQqKfDQ4oWBnfQqX25hbtA189WxA8',
    appId: '1:188098793596:ios:2e482f667b7e6148df39f9',
    messagingSenderId: '188098793596',
    projectId: 'minchat-8ea90',
    storageBucket: 'minchat-8ea90.appspot.com',
    iosBundleId: 'br.com.thomazdevelop.minimalChat',
  );
}
